package myrasec

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/Myra-Security-GmbH/myrasec-go/v2/pkg/types"
)

// getDNSRecordMethods returns DNS record related API calls
func getDNSRecordMethods() map[string]APIMethod {
	return map[string]APIMethod{
		"getDNSRecord": {
			Name:               "getDNSRecord",
			Action:             "domain/%d/dns-records/%d",
			Method:             http.MethodGet,
			Result:             DNSRecord{},
			ResponseDecodeFunc: decodeSingleElementResponse,
		},
		"listDNSRecords": {
			Name:   "listDNSRecords",
			Action: "domain/%d/dns-records",
			Method: http.MethodGet,
			Result: []DNSRecord{},
		},
		"createDNSRecord": {
			Name:   "createDNSRecord",
			Action: "domain/%d/dns-records",
			Method: http.MethodPost,
			Result: DNSRecord{},
		},
		"updateDNSRecord": {
			Name:   "updateDNSRecord",
			Action: "domain/%d/dns-records/%d",
			Method: http.MethodPut,
			Result: DNSRecord{},
		},
		"deleteDNSRecord": {
			Name:   "deleteDNSRecord",
			Action: "domain/%d/dns-records/%d",
			Method: http.MethodDelete,
			Result: DNSRecord{},
		},
	}
}

// DNSRecord represents a single DNS entry within a domain zone.
// It supports various record types including standard records (A, CNAME)
// and specialized security records (CAA, DS).
type DNSRecord struct {
	// ID is the unique identifier for the DNS record.
	// This value is server-generated and required for update and delete operations.
	ID int `json:"id,omitempty" jsonschema:"The unique identifier for the DNS record. Server-generated; required for updates and deletes, but ignored during creation."`

	// Created indicates when the record was added.
	// This is a server-managed, read-only value in ISO 8601 format.
	Created *types.DateTime `json:"created,omitempty" jsonschema:"The timestamp of creation (ISO 8601 format). This is a server-managed, read-only value."`

	// Modified serves as a version identifier for optimistic locking.
	// It records the last update time in ISO 8601 format. This field is required
	// for update and delete operations to ensure data consistency.
	Modified *types.DateTime `json:"modified,omitempty" jsonschema:"The last update timestamp (ISO 8601 format). Required for updates and deletes to ensure data consistency (optimistic locking)."`

	// Name is the subdomain or host name (e.g., "www" or "@" for the root domain).
	Name string `json:"name" jsonschema:"The subdomain name (e.g., 'www', 'mail') or '@' for the root domain."`

	// Value is the target data for the record.
	// Depending on RecordType, this can be an IP address, domain name, or text.
	Value string `json:"value" jsonschema:"The record content, such as an IP address, domain name, or text value."`

	// RecordType specifies the DNS resource record type.
	// Valid values include A, AAAA, MX, CNAME, TXT, NS, SRV, PTR and DS.
	RecordType string `json:"recordType" jsonschema:"The DNS record type. Allowed values: 'A', 'AAAA', 'MX', 'CNAME', 'TXT', 'NS', 'SRV', 'PTR', 'DS'. Note: PTR is only valid for .arpa domains."`

	// AlternativeCNAME indicates an alias pointing to this record.
	// This is a read-only attribute generated by the API.
	AlternativeCNAME string `json:"alternativeCname,omitempty" jsonschema:"An alternative CNAME pointing to this record. This is a read-only, server-generated value."`

	// Comment is an optional text to describe the purpose of this record.
	Comment string `json:"comment,omitempty" jsonschema:"An optional comment or description for this DNS record."`

	// CAATag specifies the property tag for CAA records.
	// Example values: "issue", "issuewild", "iodef".
	CAATag string `json:"caaTag,omitempty" jsonschema:"The property tag for CAA records. Allowed values: 'issue', 'issuewild', 'issuemail', 'issuevmc', 'iodef', 'contactemail', 'contactphone'."`

	// Active indicates if the record is proxied/protected by the Myra WAF.
	Active bool `json:"active" jsonschema:"If true, the record is proxied and protected by the Myra WAF/CDN. If false, it is DNS-only."`

	// Enabled determines if the DNS record is active in the zone.
	Enabled bool `json:"enabled" jsonschema:"Determines whether this DNS record is enabled (published) or disabled."`

	// TTL (Time To Live) defines the cache duration in seconds for DNS resolvers.
	TTL int `json:"ttl" jsonschema:"The Time To Live (TTL) in seconds. Controls how long DNS resolvers cache this record."`

	// Priority specifies the priority for MX and SRV records.
	// Lower values typically indicate higher priority.
	Priority int `json:"priority,omitempty" jsonschema:"Priority value. Required for MX and SRV records."`

	// Port defines the service port for SRV records.
	Port int `json:"port,omitempty" jsonschema:"Service port. Required for SRV records."`

	// Weight defines the relative weight for SRV records with the same priority.
	Weight int `json:"weight,omitempty" jsonschema:"Weight value. Required for SRV records."`

	// CAAFlags represents the flag byte for CAA records (usually 0 or 128).
	CAAFlags int `json:"caaFlags,omitempty" jsonschema:"Flags for CAA records (e.g., 0 for non-critical, 128 for critical)."`

	// Encryption specifies the algorithm ID for DS records.
	// Common values: 8 (RSA/SHA-256), 13 (ECDSA-P256/SHA256).
	Encryption int `json:"encryption,omitempty" jsonschema:"Algorithm ID for DS records. Common values: 3 (DSA/SHA1), 5 (RSA/SHA1), 8 (RSA/SHA-256), 10 (RSA/SHA-512), 13 (ECDSA-P256), 15 (ED25519)."`

	// HashType specifies the digest type ID for DS records.
	// Values: 1 (SHA-1), 2 (SHA-256), 3 (GOST), 4 (SHA-384).
	HashType int `json:"hashType,omitempty" jsonschema:"Digest type ID for DS records. Allowed values: 1 (SHA-1), 2 (SHA-256), 3 (GOST), 4 (SHA-384)."`

	// IdentificationNumber is the Key Tag for DS records.
	IdentificationNumber int `json:"identificationNumber,omitempty" jsonschema:"The Key Tag (ID) for DS records."`

	// Endpoints lists the Myra IP addresses serving this record, keyed by IP version ("ipv4"/"ipv6").
	// This is a read-only, server-generated value returned for A, AAAA and CNAME records.
	Endpoints DNSRecordEndpoints `json:"endpoints,omitempty" jsonschema:"The Myra IP addresses serving this record, keyed by IP version ('ipv4'/'ipv6'). Read-only, server-generated; returned for A, AAAA and CNAME records."`

	// UpstreamOptions configures load balancing behavior for the origin.
	UpstreamOptions *UpstreamOptions `json:"upstreamOptions,omitempty" jsonschema:"Configuration for load balancing and origin behavior (failover, weights) for this record."`
}

// DNSRecordEndpoints maps an IP version ("ipv4"/"ipv6") to the Myra IP addresses
// serving a DNS record.
type DNSRecordEndpoints map[string][]string

// UnmarshalJSON decodes the endpoints attribute of a DNS record.
//
// The API serializes the attribute as a JSON object, but sends an empty JSON array
// instead of an empty object when a record has no endpoints - for example for TXT
// records or in the response to a create request. Both shapes are accepted. Every
// representation of "no endpoints" ([], {} and null) decodes to a nil map, so a nil
// check is enough to test for an empty result.
func (e *DNSRecordEndpoints) UnmarshalJSON(data []byte) error {
	if len(data) > 0 && data[0] == '[' {
		var elements []json.RawMessage
		if err := json.Unmarshal(data, &elements); err != nil {
			return err
		}

		if len(elements) > 0 {
			return fmt.Errorf("unexpected non-empty array for DNS record endpoints: %s", data)
		}

		*e = nil

		return nil
	}

	var endpoints map[string][]string
	if err := json.Unmarshal(data, &endpoints); err != nil {
		return err
	}

	if len(endpoints) == 0 {
		*e = nil

		return nil
	}

	*e = endpoints

	return nil
}

// UpstreamOptions controls the load balancing and failover behavior
// for origin servers associated with a DNS record.
type UpstreamOptions struct {
	// ID is the unique identifier for the upstream option.
	ID int `json:"id,omitempty" jsonschema:"The unique identifier for the upstream option. Server-generated; required for updates/deletes."`

	// Created indicates when the configuration was added.
	// This is a server-managed, read-only value.
	Created *types.DateTime `json:"created,omitempty" jsonschema:"The timestamp of creation (ISO 8601 format). Server-managed, read-only."`

	// Modified serves as a version identifier.
	// Required for update and delete operations.
	Modified *types.DateTime `json:"modified,omitempty" jsonschema:"The last update timestamp (ISO 8601 format). Required for updates and deletes to ensure data consistency."`

	// Backup marks the server as a failover standby.
	// It only receives traffic if primary servers are unavailable.
	Backup bool `json:"backup" jsonschema:"If true, marks this origin as a backup server. It receives traffic only when primary servers are unavailable."`

	// Down marks the server as administratively unavailable.
	Down bool `json:"down" jsonschema:"If true, marks the origin server as permanently unavailable (maintenance mode)."`

	// FailTimeout defines the time window for counting failure attempts
	// and the duration the server is considered unavailable.
	// Example format: "10s", "1m".
	FailTimeout string `json:"failTimeout" jsonschema:"The time window for counting failure attempts (e.g., '10s', '1m'). Also defines how long the server remains 'unavailable' after reaching MaxFails."`

	// MaxFails is the threshold of unsuccessful attempts within FailTimeout
	// before the server is considered unavailable.
	MaxFails int `json:"maxFails" jsonschema:"The number of failed attempts allowed within the 'failTimeout' window before the server is marked unavailable."`

	// Weight assigns a relative priority to the origin server.
	// Higher values indicate a higher proportion of traffic.
	Weight int `json:"weight" jsonschema:"The load balancing weight. Higher numbers receive a larger proportion of traffic."`
}

// GetDNSRecord returns a single DNS record with/for the given identifier
func (api *API) GetDNSRecord(domainId int, id int) (*DNSRecord, error) {
	if _, ok := api.methods["getDNSRecord"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "getDNSRecord")
	}

	definition := api.methods["getDNSRecord"]
	definition.Action = fmt.Sprintf(definition.Action, domainId, id)

	result, err := api.call(definition, map[string]string{})
	if err != nil {
		return nil, err
	}

	res, ok := result.(*DNSRecord)
	if !ok {
		return nil, fmt.Errorf("unexpected result type %T", result)
	}
	return res, nil
}

// ListDNSRecords returns a slice containing all visible DNS records for a domain
func (api *API) ListDNSRecords(domainId int, params map[string]string) ([]DNSRecord, error) {
	if _, ok := api.methods["listDNSRecords"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "listDNSRecords")
	}

	definition := api.methods["listDNSRecords"]
	definition.Action = fmt.Sprintf(definition.Action, domainId)

	result, err := api.call(definition, params)
	if err != nil {
		return nil, err
	}

	res, ok := result.(*[]DNSRecord)
	if !ok {
		return nil, fmt.Errorf("unexpected result type %T", result)
	}
	return *res, nil
}

// CreateDNSRecord creates a new DNS record using the MYRA API
func (api *API) CreateDNSRecord(record *DNSRecord, domainId int) (*DNSRecord, error) {
	if _, ok := api.methods["createDNSRecord"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "createDNSRecord")
	}

	definition := api.methods["createDNSRecord"]
	definition.Action = fmt.Sprintf(definition.Action, domainId)

	result, err := api.call(definition, record)
	if err != nil {
		return nil, err
	}
	res, ok := result.(*DNSRecord)
	if !ok {
		return nil, fmt.Errorf("unexpected result type %T", result)
	}
	return res, nil
}

// UpdateDNSRecord updates the passed DNS record using the MYRA API
func (api *API) UpdateDNSRecord(record *DNSRecord, domainId int) (*DNSRecord, error) {
	if _, ok := api.methods["updateDNSRecord"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "updateDNSRecord")
	}

	definition := api.methods["updateDNSRecord"]
	definition.Action = fmt.Sprintf(definition.Action, domainId, record.ID)

	result, err := api.call(definition, record)
	if err != nil {
		return nil, err
	}
	res, ok := result.(*DNSRecord)
	if !ok {
		return nil, fmt.Errorf("unexpected result type %T", result)
	}
	return res, nil
}

// DeleteDNSRecord deletes the passed DNS record using the MYRA API
func (api *API) DeleteDNSRecord(record *DNSRecord, domainId int) (*DNSRecord, error) {
	if _, ok := api.methods["deleteDNSRecord"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "deleteDNSRecord")
	}

	definition := api.methods["deleteDNSRecord"]
	definition.Action = fmt.Sprintf(definition.Action, domainId, record.ID)

	_, err := api.call(definition, record)
	if err != nil {
		return nil, err
	}
	return record, nil
}
