package myrasec

import (
	"fmt"
	"net/http"

	"github.com/Myra-Security-GmbH/myrasec-go/v2/pkg/types"
)

// getDNSRecordMethods returns DNS record related API calls
func getDNSRecordMethods() map[string]APIMethod {
	return map[string]APIMethod{
		"getDNSRecord": {
			Name:               "getDNSRecord",
			Action:             "domain/%d/dns-records/%d",
			Method:             http.MethodGet,
			Result:             DNSRecord{},
			ResponseDecodeFunc: decodeSingleElementResponse,
		},
		"listDNSRecords": {
			Name:   "listDNSRecords",
			Action: "domain/%d/dns-records",
			Method: http.MethodGet,
			Result: []DNSRecord{},
		},
		"createDNSRecord": {
			Name:   "createDNSRecord",
			Action: "domain/%d/dns-records",
			Method: http.MethodPost,
			Result: DNSRecord{},
		},
		"updateDNSRecord": {
			Name:   "updateDNSRecord",
			Action: "domain/%d/dns-records/%d",
			Method: http.MethodPut,
			Result: DNSRecord{},
		},
		"deleteDNSRecord": {
			Name:   "deleteDNSRecord",
			Action: "domain/%d/dns-records/%d",
			Method: http.MethodDelete,
			Result: DNSRecord{},
		},
	}
}

// DNSRecord ...
type DNSRecord struct {
	ID                   int              `json:"id,omitempty" jsonschema:"ID is an unique identifier for an object. This value is always a number type and cannot be set while inserting a new object. To update or delete a DnsRecord it is necessary to add this attribute to your object."`
	Created              *types.DateTime  `json:"created,omitempty" jsonschema:"Created is a date type attribute with an ISO 8601 format. It will be created by the server when creating a new DnsRecord object. This value is only informational so it is not necessary to add this an attribute to any API call."`
	Modified             *types.DateTime  `json:"modified,omitempty" jsonschema:"Identifies the version of the object. To ensure that you are updating the most recent version and not overwriting other changes, you always have to add modified for updates and deletions. This value is always a date type with an ISO 8601 format."`
	Name                 string           `json:"name" jsonschema:"Subdomain name of a DNS record."`
	Value                string           `json:"value" jsonschema:"The values in the format of an IP address, name, or text for the DNS entry."`
	RecordType           string           `json:"recordType" jsonschema:"This value sets the type of the DNS record. All available record types are A, AAAA, MX, CNAME, TXT, NS, SRV, PTR and DS. PTR records are only useable on .arpa domains."`
	AlternativeCNAME     string           `json:"alternativeCname,omitempty" jsonschema:"The alternative CNAME that points to the current record. This attribute is generated by the API and cannot be set."`
	Comment              string           `json:"comment,omitempty" jsonschema:"A comment to describe this DNS record."`
	CAATag               string           `json:"caaTag,omitempty" jsonschema:"Tag value for CAA records. Available values are issue, issuewild, issuemail, issuevmc, iodef, contactemail and contactphone"`
	Active               bool             `json:"active" jsonschema:"This information shows if this record is protected by Myra."`
	Enabled              bool             `json:"enabled" jsonschema:"Define wether this DNS record is enabled or not."`
	TTL                  int              `json:"ttl" jsonschema:"Time to live limits the time a DNS record entry can be cached by DNS servers. This typically sets the timeframe how long changes need to be propagated to the DNS servers. This is a numeric value and is given in seconds."`
	Priority             int              `json:"priority,omitempty" jsonschema:"Priority for MX and SRV records."`
	Port                 int              `json:"port,omitempty" jsonschema:"Port information for SRV records."`
	Weight               int              `json:"weight,omitempty" jsonschema:"Weight for SRV records."`
	CAAFlags             int              `json:"caaFlags,omitempty" jsonschema:"Flags value for CAA records."`
	Encryption           int              `json:"encryption,omitempty" jsonschema:"Encryption for DS records. Available values are 3 (DSA/SHA1), 5 (RSA/SHA1), 6 (DSA-NSEC3-SHA1), 7 (RSASHA1-NSEC3-SHA1), 8 (RSA/SHA-256), 10 (RSA/SHA-512), 12 (GOST R 35.10-2001), 13 (ECDSA-P256/SHA256), 14 (ECDSA-P384/SHA384), 15 (ED25519) and 16 (ED448)."`
	HashType             int              `json:"hashType,omitempty" jsonschema:"Hash type for DS records. Available values are 1 (SHA-1), 2 (SHA-256), 3 (GOST R 34.11-94) and 4 (SHA-384)."`
	IdentificationNumber int              `json:"identificationNumber,omitempty" jsonschema:"ID (key tag) for DS records."`
	UpstreamOptions      *UpstreamOptions `json:"upstreamOptions,omitempty" jsonschema:"The load balance setting lets you configure the way different IP addresses pointing to the same DNS record name behave."`
}

// UpstreamOptions ...
type UpstreamOptions struct {
	ID          int             `json:"id,omitempty" jsonschema:"ID is an unique identifier for an object. This value is always a number type and cannot be set while inserting a new object. To update or delete a UpstreamOptions object, it is necessary to add this attribute to your object."`
	Created     *types.DateTime `json:"created,omitempty" jsonschema:"Created is a date type attribute with an ISO 8601 format. Created will be created by the server after creating a new UpstreamOptions object. This value is only informational so it is not necessary to add this an attribute to any API call."`
	Modified    *types.DateTime `json:"modified,omitempty" jsonschema:"Identifies the version of the object. To ensure that you are updating the most recent version and not overwriting other changes, you always have to add modified for updates and deletions. This value is always a date type with an ISO 8601 format."`
	Backup      bool            `json:"backup" jsonschema:"Marks the origin server as backup. The servers marked as backup will receive the requests when the primary servers are unavailable."`
	Down        bool            `json:"down" jsonschema:"Marks the origin server as permanently unavailable."`
	FailTimeout string          `json:"failTimeout" jsonschema:"The time during which the specified number of unsuccessful attempts to communicate with the origin should happen to consider the origin unavailable and the period of time the origin will be considered unavailable."`
	MaxFails    int             `json:"maxFails" jsonschema:"Sets the number of unsuccessful attempts to communicate with the origin that should happen in the duration set by the failTimeout parameter to consider the origin unavailable for a duration also set by the failTimeout parameter."`
	Weight      int             `json:"weight" jsonschema:"Defines the priority for the origin server, the higher the number, the higher the priority of the server."`
}

// GetDNSRecord returns a single DNS record with/for the given identifier
func (api *API) GetDNSRecord(domainId int, id int) (*DNSRecord, error) {
	if _, ok := methods["getDNSRecord"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "getDNSRecord")
	}

	definition := methods["getDNSRecord"]
	definition.Action = fmt.Sprintf(definition.Action, domainId, id)

	result, err := api.call(definition, map[string]string{})
	if err != nil {
		return nil, err
	}

	return result.(*DNSRecord), nil
}

// ListDNSRecords returns a slice containing all visible DNS records for a domain
func (api *API) ListDNSRecords(domainId int, params map[string]string) ([]DNSRecord, error) {
	if _, ok := methods["listDNSRecords"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "listDNSRecords")
	}

	definition := methods["listDNSRecords"]
	definition.Action = fmt.Sprintf(definition.Action, domainId)

	result, err := api.call(definition, params)
	if err != nil {
		return nil, err
	}

	return *result.(*[]DNSRecord), nil
}

// CreateDNSRecord creates a new DNS record using the MYRA API
func (api *API) CreateDNSRecord(record *DNSRecord, domainId int) (*DNSRecord, error) {
	if _, ok := methods["createDNSRecord"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "createDNSRecord")
	}

	definition := methods["createDNSRecord"]
	definition.Action = fmt.Sprintf(definition.Action, domainId)

	result, err := api.call(definition, record)
	if err != nil {
		return nil, err
	}
	return result.(*DNSRecord), nil
}

// UpdateDNSRecord updates the passed DNS record using the MYRA API
func (api *API) UpdateDNSRecord(record *DNSRecord, domainId int) (*DNSRecord, error) {
	if _, ok := methods["updateDNSRecord"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "updateDNSRecord")
	}

	definition := methods["updateDNSRecord"]
	definition.Action = fmt.Sprintf(definition.Action, domainId, record.ID)

	result, err := api.call(definition, record)
	if err != nil {
		return nil, err
	}
	return result.(*DNSRecord), nil
}

// DeleteDNSRecord deletes the passed DNS record using the MYRA API
func (api *API) DeleteDNSRecord(record *DNSRecord, domainId int) (*DNSRecord, error) {
	if _, ok := methods["deleteDNSRecord"]; !ok {
		return nil, fmt.Errorf("passed action [%s] is not supported", "deleteDNSRecord")
	}

	definition := methods["deleteDNSRecord"]
	definition.Action = fmt.Sprintf(definition.Action, domainId, record.ID)

	_, err := api.call(definition, record)
	if err != nil {
		return nil, err
	}
	return record, nil
}
